### ISSUE TITLE
Server crash: `NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo`

### ISSUE THREAD

**Issue by Krutoy242** [GlodBlock/DeepMobEvolution-Blood#7]
After 2 updates, server cant start with error:

```less
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Deep Blood Evolution (deepmoblearningbm)
Caused by: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
    at com.glodblock.github.dmeblood.DeepMobLearningBM.preInit(DeepMobLearningBM.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

[crash-2023-03-30_18.30.34-server.txt](https://github.com/GlodBlock/DeepMobEvolution-Blood/files/11115348/crash-2023-03-30_18.30.34-server.txt)

**Comment by GlodBlock** [comment]
fixed in 1.1.3
